import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import SwiperComponent from '../components/swiper/swiper'
import MainLayout from '../layouts/MainLayout'
import styles from '../styles/welcome.module.scss'

const Home: NextPage = ({estates}:any) => {
    const [firstName, setFirstName] = useState('')
	const [lastName, setLastName] = useState('')
	const [phone, setPhone] = useState('')
	const [email, setEmail] = useState('')
	const [message, setMessage] = useState('')

    const onSubmitHandler = async (e:any) => {
        e.preventDefault()
        const res = await fetch('../../api/message/create', {
			method: 'POST',
			body: JSON.stringify({propertyId: null, firstName, lastName, phone, email, message}),
			headers: {'Content-Type': 'application/json'}
		})
        const response = await res.json()
    }
    
    return (
        <MainLayout>
            <Head>
                <title>Contacts | Hannibal Properties</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className={styles.thanking}>
                    <div className={styles.title}>
                        THANK YOU FOR REACHING HANNIBAL PROPERTIES
                    </div>
                    <div className={styles.subtitle}>
                        Using the form below, please provide as much detailed information as possible. The information you submit may be shared with our independently owned and operated franchisee so that your concerns can be addressed. <br /><br />
                        Please note that by providing your phone number and email address, you are providing consent for us to reach out to you via this method.
                    </div>
                </div>
                <div className={styles.form}>
                    <form onSubmit={(e) => onSubmitHandler(e)} method='POST'>
                        <input
                            type="text"
                            placeholder="*First Name"
                            value={firstName}
                            onChange={(e) => setFirstName(e.target.value)}
                            required
                        />
                        <input
                            type="text"
                            placeholder="*Last Name"
                            value={lastName}
                            onChange={(e) => setLastName(e.target.value)}
                            required
                        />
                        <input
                            type="phone"
                            placeholder="Phone"
                            value={phone}
                            onChange={(e) => setPhone(e.target.value)}
                            required
                        />
                        <input
                            type="email"
                            placeholder="*Email"
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            required
                        />
                        <textarea
                            cols={30}
                            rows={10}
                            placeholder="Your message"
                            value={message}
                            onChange={(e) => {
                                if (e.target.value.length < 500) {setMessage(e.target.value)}
                            }}
                        ></textarea> <br />
                        <input type="submit" value="SEND" />
                    </form>

                    
                </div>
            </main>
        </MainLayout>
        
    )
}

export default Home

export async function getStaticProps(context: any) {
    const res = await fetch(`http://localhost:5000/properties`)
    const estates = await res.json()
  
    return { props: { estates }}
  
}
