import type { NextPage } from 'next'
import Link from 'next/link'
import MainLayout from '../../layouts/MainLayout'
import styles from '/styles/properties-list.module.scss'
import PropertiesList from '../../components/properties/list'
import Filters from '../../components/Filters'
import { useState } from 'react'
import Head from 'next/head'

const PropertiesPage: NextPage = ({estates}:any) => {

	console.log("RENDER")
	return (
		<MainLayout>
			<Head>
                <title>Properties | Hannibal Properties</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
			<div className={styles.container}>
				{/* <div className={styles.filtersContainer}>
					<Filters />
				</div> */}
				<div className={styles.listContainer}>
					<div className={styles.list}>
						<PropertiesList {...estates}/>
					</div>
				</div>
			</div>

		</MainLayout>
	)
} 

export default PropertiesPage

export async function getStaticProps() {

  const res = await fetch(`http://localhost:5000/properties`)
  const estates = await res.json()

  return { props: { estates }}

}

